env: flex
runtime: custom
entrypoint: npm run start:prod

resources:
  cpu: 2
  memory_gb: 5
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10

env_variables:
  NODE_ENV: 'production'
  PROD_JWT_SECRET_KEY: 'shida17_prod'
  CLOUD_SQL_CONNECTION_NAME: 'nest-crud-jwt-swagger-gcp:us-central1:biblioteca-instancia'  # Correcto
  DATABASE_PORT: '3306'
  DATABASE_USER: 'root'
  DATABASE_PASSWORD: 'shida17'
  DATABASE_NAME: 'biblioteca'

# Conector de Cloud SQL para conexiones serverless
cloud_sql_instances: 'nest-crud-jwt-swagger-gcp:us-central1:biblioteca-instancia'

liveness_check:
  path: "/api/v1/health"
  check_interval_sec: 25
  failure_threshold: 3
  success_threshold: 2
