env: flex
runtime: custom
entrypoint: npm run start:prod

# Recursos asignados
resources:
  cpu: 2
  memory_gb: 5
  disk_size_gb: 10

# Conexi칩n a la red VPC (sin vpc_access_connector, ya que no es compatible con flex)
network:
  name: default  # Nombre de la red VPC

# Configuraci칩n de escalado autom치tico
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10

# Variables de entorno
env_variables:
  NODE_ENV: 'production'
  PROD_JWT_SECRET_KEY: 'shida17_prod'
  DATABASE_HOST: '10.54.128.2'  # IP privada de tu instancia de Cloud SQL
  DATABASE_PORT: '3306'
  DATABASE_USER: 'root'
  DATABASE_PASSWORD: 'shida17'
  DATABASE_NAME: 'biblioteca'

# Verificaci칩n de salud
liveness_check:
  path: "/api/v1/health"
  check_interval_sec: 25
  failure_threshold: 3
  success_threshold: 2
