env: flex
runtime: custom
entrypoint: npm run start:prod

# Recursos asignados
resources:
  cpu: 2
  memory_gb: 5
  disk_size_gb: 10

# Conexión a la red VPC
network:
  name: default  # Usa la red VPC por defecto

# Configuración de escalado automático
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10

# Variables de entorno para conexión por IP privada
env_variables:
  NODE_ENV: 'production'
  PROD_JWT_SECRET_KEY: 'shida17_prod'
  DATABASE_HOST: '10.54.128.2'  # IP privada de Cloud SQL
  DATABASE_PORT: '3306'
  DATABASE_USER: 'root'
  DATABASE_PASSWORD: 'shida17'
  DATABASE_NAME: 'biblioteca'

# Verificación de salud
liveness_check:
  path: "/api/v1/health"
  check_interval_sec: 25
  failure_threshold: 3
  success_threshold: 2
