env: flex
runtime: custom
entrypoint: npm run start:prod

# Recursos asignados
resources:
  cpu: 2
  memory_gb: 5
  disk_size_gb: 10

# Conexión a la red VPC
network:
  name: default  # Usa la red VPC por defecto

# Configuración de escalado automático
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10

# Variables de entorno para Cloud SQL Auth Proxy y conexión por IP privada
env_variables:
  NODE_ENV: 'production'
  PROD_JWT_SECRET_KEY: 'shida17_prod'
  DATABASE_HOST: '127.0.0.1'  #
  DATABASE_PORT: '3306'
  DATABASE_USER: 'root'
  DATABASE_PASSWORD: 'shida17'
  DATABASE_NAME: 'biblioteca'
  INSTANCE_CONNECTION_NAME: 'crud-api-biblioteca-nest:us-central1:biblioteca-instancia'  # Nombre de la conexión Cloud SQL

beta_settings:
  cloud_sql_instances: 'crud-api-biblioteca-nest:us-central1:biblioteca-instancia'  # Nombre de la instancia de Cloud SQL (el mismo que en las variables de entorno)

# Verificación de salud
liveness_check:
  path: "/api/v1/health"
  check_interval_sec: 25
  failure_threshold: 3
  success_threshold: 2
