env: flex
runtime: custom
entrypoint: npm run start:prod

# Recursos asignados
resources:
  cpu: 2
  memory_gb: 5
  disk_size_gb: 10

# Conexión a la red VPC (sin vpc_access_connector, ya que no es compatible con flex)
network:
  name: default  # Asegúrate de que sea la red correcta

# Configuración de escalado automático
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10

# Variables de entorno
env_variables:
  NODE_ENV: 'production'
  PROD_JWT_SECRET_KEY: 'shida17_prod'
  CLOUD_SQL_CONNECTION_NAME: 'nest-crud-jwt-swagger-gcp:us-central1:biblioteca-instancia'
  DATABASE_PORT: '3306'
  DATABASE_USER: 'root'
  DATABASE_PASSWORD: 'shida17'
  DATABASE_NAME: 'biblioteca'

# Verificación de salud (sin 'path' para liveness y readiness, pero con 'path' para health_check)
liveness_check:
  check_interval_sec: 30
  timeout_sec: 20
  failure_threshold: 5
  success_threshold: 2

readiness_check:
  check_interval_sec: 30
  timeout_sec: 20
  failure_threshold: 5
  success_threshold: 2

# Verificación de inicio (con 'path' específico)
health_check:
  path: "/api/v1/health"        # Ruta de verificación de salud
  check_interval_sec: 30
  timeout_sec: 20
  failure_threshold: 5
  success_threshold: 2
  initial_delay_sec: 120         # Retraso inicial antes de la primera verificación
