steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/crud-api-biblioteca-nest/crud-api-biblioteca-nest:latest', '.']

  # Paso 2: Subir la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/crud-api-biblioteca-nest/crud-api-biblioteca-nest:latest']

  # Paso 3: Desplegar la imagen Docker en App Engine y capturar errores
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Detiene la ejecución si hay un error
        echo "Iniciando despliegue en App Engine..."
        gcloud app deploy --image-url=gcr.io/crud-api-biblioteca-nest/crud-api-biblioteca-nest:latest --project=crud-api-biblioteca-nest --quiet --verbosity=debug || { echo "Error durante el despliegue."; exit 1; }
        echo "Despliegue completado exitosamente."  # Mensaje de éxito

options:
  logging: CLOUD_LOGGING_ONLY  # Usa solo Cloud Logging para los registros
