steps:
  # Paso 1: Construir la imagen Docker usando el Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/nest-crud-jwt-swagger-gcp/crud-api-biblioteca-nest:latest', '.']

  # Paso 2: Subir la imagen a Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/nest-crud-jwt-swagger-gcp/crud-api-biblioteca-nest:latest']

  # Paso 3: Desplegar la imagen Docker en App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'app'
      - 'deploy'
      - '--image-url=gcr.io/nest-crud-jwt-swagger-gcp/crud-api-biblioteca-nest:latest'
      - '--project=nest-crud-jwt-swagger-gcp'
      - '--quiet'

  # Paso 4: Ejecutar migraciones en la base de datos Cloud SQL
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['run', 'migrate']
    env:
      - 'CLOUD_SQL_CONNECTION_NAME=nest-crud-jwt-swagger-gcp:us-central1:biblioteca-instancia'
      - 'DATABASE_PORT=3306'
      - 'DATABASE_USER=root'
      - 'DATABASE_PASSWORD=shida17'
      - 'DATABASE_NAME=biblioteca'

timeout: 1200s  # Tiempo máximo para completar el build (20 minutos)
options:
  logging: CLOUD_LOGGING_ONLY  # Usa solo Cloud Logging para manejar los registros de la compilación
