steps:
  # Paso 1: Construir la imagen con soporte de red
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'NODE_ENV=production', '--build-arg', 'PROD_JWT_SECRET_KEY=shida17_prod', '--build-arg', 'DATABASE_USER=root', '--build-arg', 'DATABASE_PASSWORD=shida17', '--build-arg', 'DATABASE_NAME=biblioteca', '--build-arg', 'CLOUD_SQL_CONNECTION_NAME=biblioteca-nest:us-central1:biblioteca-nest', '--build-arg', 'LOGGING_LEVEL=debug', '-t', 'gcr.io/biblioteca-nest/biblioteca-nest', '.']

  # Paso 2: Subir la imagen a Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/biblioteca-nest/biblioteca-nest']

  # Paso 3: Desplegar en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'biblioteca-nest',
      '--image', 'gcr.io/biblioteca-nest/biblioteca-nest',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--set-env-vars', 'NODE_ENV=production,PROD_JWT_SECRET_KEY=shida17_prod,DATABASE_USER=root,DATABASE_PASSWORD=shida17,DATABASE_NAME=biblioteca,CLOUD_SQL_CONNECTION_NAME=biblioteca-nest:us-central1:biblioteca-nest,LOGGING_LEVEL=debug',
      '--quiet'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
